CREATE DATABASE futdex;

USE futdex;

CREATE TABLE CAMPEONATO (
	Id	  INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nome  VARCHAR(30) NOT NULL UNIQUE,
);

CREATE TABLE TIME (
    Id	  INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nome  VARCHAR(30) NOT NULL UNIQUE,
    CampeonatoId INT UNSIGNED NOT NULL,
    FOREIGN KEY (CampeonatoId) REFERENCES CAMPEONATO(Id)
);
